### PR TITLE
Don't require a delay for auto-update

### PR DESCRIPTION
**Pull request by antoine-levitt**

### CODE REVIEW

**Comment by retorquere** [comment]
I'd prefer it if the PR came with an explanation why this would be a good idea? There are good reasons for this delay. It prevents overlapping auto-exports starting. Syncing items with Zotero storage with delay at 0 would cause mayhem, and Zotero is already pretty critical of the performance imposition of auto export.

**Comment by antoine-levitt** [comment]
My use case is that I go to Google scholar to pick papers to cite, save them in zotero then go to emacs to \cite the paper I just saw, and then if I do this too fast emacs doesn't find the paper in the .bib. Waiting 2s for zotero to finish syncing then auto exporting is annoying.

I don't know how zotero is coded so I don't know how much a problem it would be. If it's necessary then maybe 1s is sufficient?

**Comment by retorquere** [comment]
You can go into the [hidden preferences](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/index.html), set `autoExportDelay` to `1`, and restart BBT. I'm not changing the slider -- it would just have people set it to 0 and cause problems.

**Comment by antoine-levitt** [comment]
Then just change it to have a minimum at 1 instead of 2?

**Comment by retorquere** [comment]
I settled on 2 because 1 still too often caused overlapping auto-exports. You can set it to 1 in hidden prefs and that will stick, it's a one-time action.

**Pull request closed without merging**
