### PR TITLE
Move journal abbreviations to Export tab

### PR DESCRIPTION
**Pull request by bwiernik**
It conceptually fits there well. I tried having a separator between the checkbox and the "Abbreviation style:" label and listbox, but thought that this looked better.

### CODE REVIEW

**Comment by bwiernik** [comment]
This is the last thing I'm planning on submitting at this point.

**Comment by retorquere** [comment]
The problem I have with this is that it's pretty big in Juris-M.

**Comment by retorquere** [comment]
(that is, the part that becomes visible in Juris-M takes up a lot of space)

**Comment by retorquere** [comment]
I have no issue with this sitting in the export pane in Zotero and in a separate pane in Juris-M, but you'de have to fiddle with [hidden](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/Preferences.ts#L260)

**Comment by bwiernik** [comment]
Okay, I tweaked it by reducing the number of rows shown on the abbreviations style list. This makes the BBT pane the same height as the Zotero Cite pane.

**Comment by retorquere** [comment]
It still stretches the prefs pane in Juris-M. I agree that it'd be good to have it in the export pane, I'm just not sure that the effect on the Juris-M prefs are better than current way,

**Comment by retorquere** [comment]
But even on Zotero, there's a significant amount of non-used space in the export pane and stretching of the cite pane.
screenshot from 2018-06-19 11-42-36
screenshot from 2018-06-19 11-42-20

**Comment by bwiernik** [comment]
That stretching is there in the current version of BBT:
image

It seems to be caused by the journal abbreviations listbox stretching the window even on Zotero when it's hidden:
image

Another option would be to convert the listbox to a menulist dropbown.

**Comment by retorquere** [comment]
That works for me.

**Comment by bwiernik** [comment]
That should work I believe.

**Comment by retorquere** [comment]
This still looks the same on Zotero for me.

**Comment by retorquere** [comment]
Looks OK on Juris-M though. Still stretches the ciet pane, but acceptably so. The way Zotero looks with it is not a breaking point for me, but if it is possible to remove that non-used space that'd be nice (not that I ever figured out how to do so myself)

**Comment by retorquere** [comment]
I've just merged it. The collapse looks better but its uncollapsed state is still used to determine the height. Very strange, but that's XUL for you.

**Comment by bwiernik** [comment]
I just noticed one more thing. I added `resizable="true"` to the two textboxes in the Advanced pane.

**Comment by retorquere** [comment]
I can either add that by hand if you tell me what to do, or it would have to be a new PR.

**Comment by bwiernik** [comment]
Lines 601 and 607 of Preferences.xul, add `resizable="true"` to the textbox elements. Or I can make a new PR.

**Comment by bwiernik** [comment]
Build 7148 is missing the resizable lines noted above. Otherwise, it looks good.

**Comment by retorquere** [comment]
> Not sure if this is expected, but the changes made in #989 are reverted in Build 7148.

They're not reverted, it's just a separate branch. When I merge to master this is resolved; I usually do a separate branch per issue, that we're doing this on master is the exception because the PR targeted master and I didn't want to complicate things.

**Comment by retorquere** [comment]
I've added the resizables but I'm not seeing any change.

**Comment by retorquere** [comment]
#989 is merged into master, you'll see that the changes from 7148 are still there. Such is the beauty of git.

**Comment by bwiernik** [comment]
They are resizable for me on Windows--perhaps resizable doesn't work correctly cross-platform?

**Comment by retorquere** [comment]
The fields are resizable for me too, but that doesn't remove the extra space that's there by default (screenshot 1), and now I can resize the text fields far enough that the resize handle and everything below it is out of screen, and there's no way to get back from that as I can't grab the now-hidden handle.

screenshot from 2018-06-19 15-43-20

screenshot from 2018-06-19 15-43-44

**Comment by bwiernik** [comment]
You’re testing on Juris-M? That extra space isn’t there for me on Zotero. If you think the default 10 lines is big enough (a scrollbar will appear), you could revert the resizable. 
		
		

		
	




On Tue, Jun 19, 2018 at 3:46 PM +0200, "Emiliano Heyns" <notifications@github.com> wrote:












The fields are resizable for me too, but that doesn't remove the extra space that's there by default (screenshot 1), and now I can resize the text fields far enough that the resize handle and everything below it is out of screen, and there's no way to get back from that as I can't grab the now-hidden handle.

**Comment by retorquere** [comment]
These screenshots are from Zotero. I test Juris-M manually only occasionally; it is tested structurally in the automated tests, but those don't test anything UI-related.

**Comment by retorquere** [comment]
Meh, this Zotero version is transitional anyway. I've reverted the resizables, good enough as-is now.

**Pull request merged**
