### PR TITLE
German Translations

### PR DESCRIPTION
**Pull request by OSHistory**

### CODE REVIEW

**Comment by retorquere** [comment]
I've manually imported the translations files -- I'm not sure whether Crowdin support reading in changes. I'll go find out, but for now this is safest.

Thanks! After import, Crowdin shows 95% done on the DTD -- could you check?

**Comment by OSHistory** [comment]
Probably English words that don't have a commonly used translation in German (or if they do, no one would get it (like URL, DOI etc.).

**Comment by retorquere** [comment]
Cool, then the translations should be submitted to github soon, and I'll put out a new release.

**Comment by retorquere** [comment]
I've cut a new release with the German translations

**Pull request closed without merging**
