### PR TITLE
Add <tt> -- \texttt{} translation

### PR DESCRIPTION
**Pull request by eelregit**
Can be useful for code names in paper titles

### CODE REVIEW

**Comment by retorquere** [comment]
Do you have a sample for this? I'd like to add it as a test case.

**Comment by eelregit** [comment]
I was trying to typeset the following reference:

```bibtex
@article{FlowPM,
  title = {\texttt{FlowPM}: Distributed Tensorflow Implementation of the \texttt{FastPM} Cosmological {{N-body}} Solver},
  author = {Modi, Chirag and Lanusse, Fran{\c c}ois and Seljak, Uro{\v s}},
  year = {2021},
  month = oct,
  journal = {Astronomy and Computing},
  volume = {37},
  eprint = {2010.11847},
  eprinttype = {arxiv},
  pages = {100505},
  issn = {2213-1337},
  doi = {10.1016/j.ascom.2021.100505},
  url = {https://www.sciencedirect.com/science/article/pii/S2213133721000597},
  urldate = {2021-12-02},
  archiveprefix = {arXiv}
}
```

Thanks for this great tool!

**Comment by retorquere** [comment]
Meaning you were trying to generate this entry, correct? Can you right-click the zotero entry that this relates to and send a support log?

**Comment by eelregit** [comment]
Done. The support log ID is `YWIJVRB8-refs-euc`.

**Comment by retorquere** [comment]
`YWIJVRB8-refs-euc` doesn't contain `<tt>` or `<code>`.

**Comment by eelregit** [comment]
The title was meant to be `<tt>FlowPM</tt>: distributed tensorflow implementation of the <tt>FastPM</tt> cosmological N-body solver`. I haven't done that because export doesn't work for <tt> yet.
Let me know if you want another support log.

**Comment by retorquere** [comment]
Ah, no need, I've added that manually now.

So, the problem is that Zotero does not support this syntax. All it supports outside rich-text notes is [this](https://www.zotero.org/support/kb/rich_text_bibliography). I could add support, but that means that the results between bibtex-rendered and zotero-rendered bibliographies would look very different here. It does work in notes with this PR applied.

A safer choice would be to also add `<span class="monospace">...</span>` or `<span style="text-transform: full-width">...</span>`, which could be used in titles (and notes, but I don't see why would you want to). It wouldn't actually work in Zotero titles, but it would just not apply the styling instead of rendering the HTML as text.

**Comment by retorquere** [comment]
A build is running that adds support for `<span class="monospace">...</span>` and `<span monospace>...</span>`.

**Pull request merged**
