### PR TITLE
Extend RPC interface to list all collections

### PR DESCRIPTION
**Pull request by wolfoo2931**
Hello,

I'm working on [MonsterWriter](https://www.monsterwriter.app/) and try to integrate the Zotero Desktop version into the app.
This change would be needed, so I could base the integration on better-bibtex.

See related issue https://github.com/retorquere/zotero-better-bibtex/issues/1941.

### CODE REVIEW

**Comment by retorquere** [comment]
I think this would work better as NSCollection.all then as NSUser.collections. They're not really user collections.

**Comment by retorquere** [comment]
I'd also recommend getting the library name along with the library ID

**Comment by wolfoo2931** [comment]
I think the library name is included already. See the example response blow. Or do you mean something else? .... I will move it into its own namespace like you suggested.

```
{
  "jsonrpc": "2.0",
  "result": [
    {
      "0": {
        "key": "U2UAB7AC",
        "version": 0,
        "name": "col",
        "parentCollection": false,
        "relations": {}
      },
      "1": {
        "key": "3NW8LI2I",
        "version": 0,
        "name": "sammlung",
        "parentCollection": false,
        "relations": {}
      },
      "2": {
        "key": "JTLT4NSZ",
        "version": 0,
        "name": "sammlung-a",
        "parentCollection": "3NW8LI2I",
        "relations": {}
      },
      "libraryID": 1
    }
  ],
  "id": null
}
```

**Comment by retorquere** [comment]
Adding an option to groups seems best to me in fact. It collects the same top-level information, and adds the collections.

**Comment by wolfoo2931** [comment]
I've extended the groups endpoint. It works like this now:

# No Parameter given
```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "user.groups", "params": [] }' | jq 
{
  "jsonrpc": "2.0",
  "result": [
    {
      "id": 1,
      "name": "Meine Bibliothek"
    }
  ],
  "id": null
}
```

# False as first parameter

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "user.groups", "params": [false] }' | jq
{
  "jsonrpc": "2.0",
  "result": [
    {
      "id": 1,
      "name": "Meine Bibliothek"
    }
  ],
  "id": null
}
```

# True as first parameter

```
curl http://localhost:23119/better-bibtex/json-rpc -X POST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary '{"jsonrpc": "2.0", "method": "user.groups", "params": [true] }' | jq
{
  "jsonrpc": "2.0",
  "result": [
    {
      "id": 1,
      "name": "Meine Bibliothek",
      "collections": [
        {
          "key": "U2UAB7AC",
          "version": 0,
          "name": "col",
          "parentCollection": false,
          "relations": {}
        },
        {
          "key": "3NW8LI2I",
          "version": 0,
          "name": "sammlung",
          "parentCollection": false,
          "relations": {}
        },
        {
          "key": "JTLT4NSZ",
          "version": 0,
          "name": "sammlung-a",
          "parentCollection": "3NW8LI2I",
          "relations": {}
        }
      ]
    }
  ],
  "id": null
}
```

**Pull request merged**
