### PR TITLE
FEATURE: Download Notes Images 

### PR DESCRIPTION
**Pull request by hasanalrasyid**
Hello,
Thank you for this great add-ons.
Actually, this is my first pull request in my whole life, so I am grateful for your understanding if there are some things that I missed or neglected.

Here is a feature to download images inside notes for the current Zotero (v6.0.8).
Maybe it is related with issue  #1856. I try to make it in sync with my own workflow.

For this purpose, I added a new route-path `collection-archive`.
The main workhorse is inside `content/image-notes.js`.
Other than the images, I also included the jzon output to keep the connection between images and the citations.

My workflow to use these files are:
1. download the base64.zip file:  `curl "http://127.0.0.1:23119/better-bibtex/export/collection-archive?/1/collectionName.biblatex&exportNotes=true"  --output collectionName.zip.base64`
2. Decode the file: `base64 -d collectionName.zip.base64 > collectionName.zip`
3. Unzip it: `unzip collectionName.zip`
4. Inside my Pandoc filter:
     * load the `collectionName.bib` as bibliography `Meta` : originalBib.
     * load the `collectionName.json` as JSON object: jsonBib
     * update `img` inside `note` of jsonBib into something accessible by LaTeX, ie: `collectionName/GU462FG3/image.png`
     * update notes inside originalBib with the new notes.

Above workflow show the necessity of `.json` as a data anchor between `.bib` and the images through `citationKey`.

All improvement suggestion is very much welcome.

Thank you very much.

### CODE REVIEW

**Comment by retorquere** [comment]
I'm willing to work together to get the open issues resolved, but I would need you to either take point on this, or express the desired functionality so I can re-implement it myself.

**Comment by retorquere** [comment]
closing for inactivity

**Comment by hasanalrasyid** [comment]
Pardon for quite long inactivity. I failed to notice the last comment.
So basically I need to take the images from annotation files.
This is just my naive attempt on this purpose. Thank you very much for your kind concern.

**Comment by retorquere** [comment]
I'm still open to the PR, but it has review comments that need resolution, and the source file you worked from has changed, so you'll have to reapply your changes to the newest version.

**Comment by retorquere** [comment]
So....?

**Comment by hasanalrasyid** [comment]
I just updated the branch to conform v6.7.28.
In this updated version, I moved to typescript.
The workflow is the same as previous.

**Comment by retorquere** [comment]
There's still a few review comments

**Comment by hasanalrasyid** [comment]
> There's still a few review comments

Pardon, which review comments did you refer to?
This is the message show on my side.
Screenshot_20221030_221015

**Comment by retorquere** [comment]
On https://github.com/retorquere/zotero-better-bibtex/pull/2166/files I see 4 open review comments. First eg

image

**Comment by retorquere** [comment]
I thought you would have received notifications for the review comments, they've been there for a while.

**Comment by hasanalrasyid** [comment]
Interestingly, I did not find your comment in my code view. Here attached my view on above link. 
OTOH, I have pushed the revision on the picture you sent.

**Comment by retorquere** [comment]
image

image

**Pull request closed without merging**
