### PR TITLE
add roam citekey option to frontend

### PR DESCRIPTION
**Pull request by lukesmurray**
Follow up to #1728. Wasn't aware I need to add the roam cite key option to the front end. Seems fairly straightforward but would appreciate a quick sanity check. Also I only speak english so I added non-translated options to the locale files.

### CODE REVIEW

**Comment by retorquere** [comment]
Only the english locale must be committed. The translations are handled through Crowdin and checking them in here may mess up their workflow.

**Comment by lukesmurray** [comment]
thanks! fixed.

**Comment by retorquere** [comment]
The translations will roll in in 10 minutes or so and then I'll cut a new release.

**Comment by retorquere** [comment]
(sorry for the lack of due diligence earlier)

**Comment by lukesmurray** [comment]
all good thanks for being so open to PRs.

**Pull request merged**
