### PR TITLE
Corrected translation of lower-case accented i such as í.

### PR DESCRIPTION
**Pull request by denisrosset**
I stumbled upon a problem when exporting a BibTeX file with "Acín" as an author (for example, a reference to this paper http://iopscience.iop.org/article/10.1088/1367-2630/10/7/073013/meta ).

I corrected the affected translation keys, but I don't know if my fix is complete --- there could be other accented characters that are affected.

### CODE REVIEW

**Comment by retorquere** [comment]
Doesn't the translation in the existing implementation render correctly? `\'` et al put an accent atop whatever character follows, and in the case of `i` and `j` the diacritic doesn't render exactly cleanly over the dot of the `i` or `j`. `\i` should render an `i` without a dot so the combined char looks nice, same thing for `\j`.

**Comment by denisrosset** [comment]
Ok... thanks I did not know the shortcut for "i without a dot". The problem happens when using a very specific implementation of BibTeX, used in TeXmacs. I'm closing this PR.

**Comment by denisrosset** [comment]
BTW, sorry for wasting your time!

**Comment by retorquere** [comment]
No time was wasted. So TexMacs doesn't support this? That's annoying. Can you open an issue for this? I'll try to come up with a workaround.

**Pull request closed without merging**
