### PR TITLE
(rephrased) indicate what means "exporting using BBT"

### PR DESCRIPTION
**Pull request by theworldisnotflat**

### CODE REVIEW

**Comment by retorquere** [comment]
It doesn't only work for "My library", it works for all libraries and collections, and may work at some point again for saved searches (but that will require a change in Zotero).

**Comment by theworldisnotflat** [comment]
sure, my intention was to clarify this point, not obvious since at that moment i was expecting a button inside the "preferences" window, not thinking at going back to the main Zotero window

**Comment by retorquere** [comment]
Back? In what sense?

**Comment by theworldisnotflat** [comment]
this section about synchronizing a bib file concerns the "preferences" box, this is where the discussion about sync takes place. This is where I arrived searching for the "how to"; It has been a bit complicated to understand that in the first place one has to  execute a regular export from the main window of Zotero, this is simply what I want to precise with this addition in the text
hoping it is more clear
thanks for you great tool by the way

**Comment by retorquere** [comment]
Only in a sense; setup of an automated export is done entirely from the export popup zotero puts up when you start an export. It's only when you want to remove an export, or change settings on it, that you need to get into the preferences. That's what confused me; your elaboration concerns the setup of the auto-export, so you wouldn't come back from the prefs screen at that stage, because that's not where it is added.

**Comment by theworldisnotflat** [comment]
the point is I searched on the internet the "how to" sync and arrived on this page about the prefs screen; this is why a ref to the popup menu is needed, in my view

**Comment by retorquere** [comment]
And I'm OK with that, but the pointer to "my library" is incomplete; I've added a comment on the change suggesting what seems the right coverage to me. If you want to change it in the PR I'll pull it in; otherwise, I'll merge this PR and make the cnage myself. What do you prefer?

**Comment by theworldisnotflat** [comment]
I am not enough familiar with git / github,  do not see where your proposed modifs are, I do not see where is your "comment on the change"
do what you feel is best; i have absolutely no reason to think that your proposal is wrong ;)

**Comment by retorquere** [comment]
That's allright, I'll take care of it. Thanks for the report, much appreciated.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.45.6831](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6831.xpi) ("Merge pull request #1580 from theworldisnotflat/patch-3\n\n(rephrased) indicate what means \"exporting using BBT\"")

Install in Zotero by downloading [test build 5.2.45.6831](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.45.6831.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Pull request merged**
